repos:
  - repo: https://github.com/psf/black
    rev: 24.10.0  # Use the latest version
    hooks:
      - id: black
        language_version: python3
        args: [--line-length=120]
        pass_filenames: true  # Only check staged files